// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVQqBEP30rMrNusCDMXMmd6kd77ZC8AY',
    appId: '1:955295317140:web:be2e0998ce2b8dcedec881',
    messagingSenderId: '955295317140',
    projectId: 'event-discrovery-app',
    authDomain: 'event-discrovery-app.firebaseapp.com',
    storageBucket: 'event-discrovery-app.firebasestorage.app',
    measurementId: 'G-Z3BPKZYV29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEe_69-F9ZlurBKcwaYIEs-gE35ZQWdvI',
    appId: '1:955295317140:android:466c245ac73f63ebdec881',
    messagingSenderId: '955295317140',
    projectId: 'event-discrovery-app',
    storageBucket: 'event-discrovery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDquZRL8EDCnLzAzfOehnmtcr2nHakVYbY',
    appId: '1:955295317140:ios:08c1fc4234c68e2ddec881',
    messagingSenderId: '955295317140',
    projectId: 'event-discrovery-app',
    storageBucket: 'event-discrovery-app.firebasestorage.app',
    iosClientId: '955295317140-f01kp6r6sj0rpoj9gqgaapd6ugrmt0ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDquZRL8EDCnLzAzfOehnmtcr2nHakVYbY',
    appId: '1:955295317140:ios:08c1fc4234c68e2ddec881',
    messagingSenderId: '955295317140',
    projectId: 'event-discrovery-app',
    storageBucket: 'event-discrovery-app.firebasestorage.app',
    iosClientId: '955295317140-f01kp6r6sj0rpoj9gqgaapd6ugrmt0ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventDiscoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVQqBEP30rMrNusCDMXMmd6kd77ZC8AY',
    appId: '1:955295317140:web:23bc8d43c3bad8abdec881',
    messagingSenderId: '955295317140',
    projectId: 'event-discrovery-app',
    authDomain: 'event-discrovery-app.firebaseapp.com',
    storageBucket: 'event-discrovery-app.firebasestorage.app',
    measurementId: 'G-9L22CPW9X0',
  );
}
